all: lab9_1 lab9_2

lab9_1: lab9_1_BlakeLevine.o
	g++ lab9_1_BlakeLevine.o -o lab9_1
lab9_1_BlakeLevine.o: lab9_1_BlakeLevine.cpp
	g++ -c lab9_1_BlakeLevine.cpp

lab9_2: lab9_2_BlakeLevine.o
	g++ lab9_1_BlakeLevine.o -o lab9_2
lab9_2_BlakeLevine.o: lab9_2_BlakeLevine.cpp
	g++ -c lab9_2_BlakeLevine.cpp
