
#lab3_1: lab3_1_Blake_Levine.o
#	g++ lab3_1_Blake_Levine.o -o lab3
#lab3_1_Blake_Levine.o: lab3_1_Blake_Levine.cpp
#	g++ -c lab3_1_Blake_Levine.cpp

#lab3_2: lab3_2_Blake_Levine.o
#	g++ lab3_2_Blake_Levine.o -o lab3
#lab3_2_Blake_Levine.o: lab3_2_Blake_Levine.cpp
#	g++ -c lab3_2_Blake_Levine.cpp

lab3_3: lab3_3_Blake_Levine.o
	g++ lab3_3_Blake_Levine.o -o lab3_3
lab3_3_Blake_Levine.o: lab3_3_Blake_Levine.cpp
	g++ -c lab3_3_Blake_Levine.cpp
