all: lab5_1 lab5_2 lab5_3

lab5_1: lab5_1_BlakeLevine.o
	g++ lab5_1_BlakeLevine.o -o lab5_1
lab5_1_BlakeLevine.o: lab5_1_BlakeLevine.cpp
	g++ -c lab5_1_BlakeLevine.cpp

lab5_2: lab5_2_BlakeLevine.o
	g++ lab5_2_BlakeLevine.o -o lab5_2
lab5_2_BlakeLevine.o: lab5_2_BlakeLevine.cpp
	g++ -c lab5_2_BlakeLevine.cpp

lab5_3: lab5_3_BlakeLevine.o
	g++ lab5_3_BlakeLevine.o -o lab5_3
lab5_3_BlakeLevine.o: lab5_3_BlakeLevine.cpp
	g++ -c lab5_3_BlakeLevine.cpp
