LABNUM = 2 
CC = g++

problem$(LABNUM): problem$(LABNUM)_BlakeLevine.o
	$(CC) problem$(LABNUM)_BlakeLevine.o -o problem$(LABNUM)
problem$(LABNUM)_BlakeLevine.o: problem$(LABNUM)_BlakeLevine.cpp
	$(CC) -c problem$(LABNUM)_BlakeLevine.cpp

