all: lab11_1 lab11_2

lab11_1: lab11_1_BlakeLevine.o
	g++ lab11_1_BlakeLevine.o -o lab11_1
lab11_1_BlakeLevine.o: lab11_1_BlakeLevine.cpp
	g++ -c lab11_1_BlakeLevine.cpp

lab11_2: lab11_2_BlakeLevine.o
	g++ lab11_2_BlakeLevine.o -o lab11_2
lab11_2_BlakeLevine.o: lab11_2_BlakeLevine.cpp
	g++ -c lab11_2_BlakeLevine.cpp
