all: lab7_1 lab7_2 lab7_3

lab7_1: lab7_1_BlakeLevine.o
	g++ lab7_1_BlakeLevine.o -o lab7_1
lab7_1_BlakeLevine.o: lab7_1_BlakeLevine.cpp
	g++ -c lab7_1_BlakeLevine.cpp

la7_2: lab7_2_BlakeLevine.o
	g++ lab7_2_BlakeLevine.o -o lab7_2
lab7_2_BlakeLevine.o: lab7_2_BlakeLevine.cpp
	g++ -c lab7_2_BlakeLevine.cpp

la7_3: lab7_3_BlakeLevine.o
	g++ lab7_3_BlakeLevine.o -o lab7_3
lab7_3_BlakeLevine.o: lab7_3_BlakeLevine.cpp
	g++ -c lab7_3_BlakeLevine.cpp

